# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nous.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: NOUS
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "사회학, 과학, 기술, 혁신, 정보, 인터넷, 오픈소스, 소프트웨어 등에 관심있는 개인 블로그입니다. / 김연철 (Yeunchul Kim)" # used by search engines

  # Header and footer text
  header_text: >
    <p>&nbsp;</P>
    <p>&nbsp;</P>
    <p>&nbsp;</P>
  header_text_feature_image: "img/main_feature_img.jpg"
  footer_text: >
    <a href="http://nous.github.io/about/">About</a> / <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "rohanchandra/type-theme"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
